pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/shireeshanare/CI-CD'
            }
        }

        stage('Build') {
            steps {
                echo 'Building project...'
                bat 'python --version'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                bat 'pytest || exit 0'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                bat '''
                    if not exist C:\\tmp\\deploy-folder mkdir C:\\tmp\\deploy-folder
                    xcopy /E /I /Y * C:\\tmp\\deploy-folder
                '''
            }
        }

    }
}
